name: deploy to lambda
on: [push]
jobs:
  deploy_source:
    name: build and deploy lambda
    strategy:
      matrix:
        node-version: [18.x]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lambda
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci --production
          npm run build --if-present
        env:
          CI: true
      - name: zip Lambda Function
        run: |
          zip -r ./bundle.zip ./ -x '*.git*'
      - name: AWS Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          aws lambda update-function-code --function-name jetbrains --zip-file fileb://bundle.zip
